In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.Parch.value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [4]:
df.drop(['Name','PassengerId','Ticket','Embarked'], axis=1, inplace=True)

In [5]:
# Encode using LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])


In [6]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin
0         0       3    1  22.0      1      0   7.2500   NaN
1         1       1    0  38.0      1      0  71.2833   C85
2         1       3    0  26.0      0      0   7.9250   NaN
3         1       1    0  35.0      1      0  53.1000  C123
4         0       3    1  35.0      0      0   8.0500   NaN

In [7]:
df.drop(['Cabin','Fare'], axis=1, inplace=True)

In [8]:
from sklearn.preprocessing import minmax_scale

df['Age'] = minmax_scale(df['Age'])

In [9]:
x = df.iloc[:, 1:]
y = df.iloc[:,0]

In [10]:
x['Age'] = x['Age'].fillna(x['Age'].mean())

In [11]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   Sex     891 non-null    int32  
 2   Age     891 non-null    float64
 3   SibSp   891 non-null    int64  
 4   Parch   891 non-null    int64  
dtypes: float64(1), int32(1), int64(3)
memory usage: 31.5 KB


In [12]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [13]:
#from sklearn.decomposition import PCA

#pca = PCA(n_components = 1)

#x = pca.fit_transform(x)
#x

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
x_train

Pclass  Sex       Age  SibSp  Parch
331       1    1  0.566474      0      0
733       2    1  0.283740      0      0
382       3    1  0.396833      0      0
704       3    1  0.321438      1      0
813       3    0  0.070118      4      2
..      ...  ...       ...    ...    ...
106       3    0  0.258608      0      0
270       1    1  0.367921      0      0
860       3    1  0.509927      2      0
435       1    0  0.170646      1      2
102       1    1  0.258608      0      1

[712 rows x 5 columns]

In [16]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 80, max_features = 15, max_depth = None, min_samples_split = 10)
model.fit(x_train, y_train)

RandomForestClassifier(max_features=15, min_samples_split=10, n_estimators=80)

In [17]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0], dtype=int64)

In [18]:
model.score(x_test, y_test)

0.8044692737430168

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[92, 13],
       [22, 52]], dtype=int64)

In [20]:
from joblib import dump
dump(model, 'Titanic_Survival_Model.joblib')

['Titanic_Survival_Model.joblib']

In [21]:
"""class RF:
    def __init__(self, name):
        self.name = name

    def RandomForestClassifier(name, n_estimators, max_features):
        model = RandomForestClassifier()
        model.fit(x_train, y_train)
        accuracy = model.score(x_test, y_test)
        print(f'The accuracy is {accuracy}')

rf1 = RF('Random Forest model')
rf1.RandomForestClassifier(input('How many trees for your RF model? '), input('How many max_features? ')) """

"class RF:\n    def __init__(self, name):\n        self.name = name\n\n    def RandomForestClassifier(name, n_estimators, max_features):\n        model = RandomForestClassifier()\n        model.fit(x_train, y_train)\n        accuracy = model.score(x_test, y_test)\n        print(f'The accuracy is {accuracy}')\n\nrf1 = RF('Random Forest model')\nrf1.RandomForestClassifier(input('How many trees for your RF model? '), input('How many max_features? ')) "

In [28]:
x_train.head()

Pclass  Sex       Age  SibSp  Parch
331       1    1  0.566474      0      0
733       2    1  0.283740      0      0
382       3    1  0.396833      0      0
704       3    1  0.321438      1      0
813       3    0  0.070118      4      2

In [27]:
y_pred = model.predict([['1','2','10','5','4']])
y_pred

c:\Users\PC\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)